apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rmq-hpa
  namespace: vprofile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vprormq-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

