apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprodb-pvc
  namespace: vprofile
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default
