apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-deployment
  namespace: game-2048
  labels:
    app: gameapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gameapp
  template:
    metadata:
      labels:
        app: gameapp
    spec:
      containers:
      - name: gameapp
        image: public.ecr.aws/kishorj/docker-2048:latest
        ports:
        - name: gameapp-port
          containerPort: 80

